# Generated by Django 4.0.5 on 2022-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='static/thumbnail/', verbose_name='썸네일')),
                ('information', models.TextField(verbose_name='정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('start_point', models.DateTimeField(verbose_name='노출 시작 일')),
                ('end_point', models.DateTimeField(verbose_name='노출 종료 일')),
                ('is_activated', models.BooleanField(verbose_name='활성화 여부')),
            ],
        ),
    ]
