# Generated by Django 4.0.5 on 2022-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
    ]
