# Generated by Django 4.0.5 on 2022-06-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_event_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('thumbnail', models.ImageField(upload_to='static/product/thumbnail/', verbose_name='썸네일')),
                ('information', models.TextField(verbose_name='상품 정보')),
                ('end_point', models.DateTimeField(verbose_name='노출 종료 일')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('is_activate', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(max_length=3, verbose_name='평점')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_activated',
            new_name='is_activate',
        ),
        migrations.AlterField(
            model_name='event',
            name='information',
            field=models.TextField(verbose_name='이벤트 정보'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='static/event/thumbnail/', verbose_name='썸네일'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('content', models.TextField(verbose_name='내용')),
                ('rating', models.SmallIntegerField(max_length=3, verbose_name='평점')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
