# Generated by Django 4.0.5 on 2022-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.SmallIntegerField(verbose_name='평점'),
        ),
    ]
