# Generated by Django 4.0.5 on 2022-06-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby',
            new_name='name',
        ),
    ]
