# Generated by Django 4.0.3 on 2022-06-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_language', models.CharField(max_length=20, verbose_name='개발 언어')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileDevLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.devlanguage')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
    ]
